name: Desarrollo

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dummy step
        run: echo "Desarrollo pipeline"
